version: "3"
services:
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    tty: true
    working_dir: /etc/letsencrypt
    volumes:
      - ./certbot/etc/letsencrypt:/etc/letsencrypt
    command: ["--version"]